//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KekuleHtml.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KekuleHtml.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number: .
        /// </summary>
        internal static string ConsolePromptEnterValidNumber {
            get {
                return ResourceManager.GetString("ConsolePromptEnterValidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the start person. &quot;0&quot; to quit..
        /// </summary>
        internal static string ConsolePromptSelectStartPerson {
            get {
                return ResourceManager.GetString("ConsolePromptSelectStartPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Kekule list for &quot;{0}&quot; was created in &quot;{1}&quot;..
        /// </summary>
        internal static string ConsoleReportCreated {
            get {
                return ResourceManager.GetString("ConsoleReportCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please pass the path to a GEDCOM file as the first parameter..
        /// </summary>
        internal static string ConsoleUsageGedcomPathRequired {
            get {
                return ResourceManager.GetString("ConsoleUsageGedcomPathRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation {0}.
        /// </summary>
        internal static string GenerationExternalName {
            get {
                return ResourceManager.GetString("GenerationExternalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grandparents.
        /// </summary>
        internal static string GenerationGrandparents {
            get {
                return ResourceManager.GetString("GenerationGrandparents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great-grandparents.
        /// </summary>
        internal static string GenerationGreatGrandparents {
            get {
                return ResourceManager.GetString("GenerationGreatGrandparents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}x great-grandparents.
        /// </summary>
        internal static string GenerationNthGreatGrandparents {
            get {
                return ResourceManager.GetString("GenerationNthGreatGrandparents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parents.
        /// </summary>
        internal static string GenerationParents {
            get {
                return ResourceManager.GetString("GenerationParents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proband.
        /// </summary>
        internal static string GenerationProband {
            get {
                return ResourceManager.GetString("GenerationProband", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (see no. {0}).
        /// </summary>
        internal static string HtmlDuplicateSeeNumber {
            get {
                return ResourceManager.GetString("HtmlDuplicateSeeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kekule list for {0}.
        /// </summary>
        internal static string HtmlHeadingKekuleListFor {
            get {
                return ResourceManager.GetString("HtmlHeadingKekuleListFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geographic distribution of the ancestral lines.
        /// </summary>
        internal static string HtmlHeadingMigrationMap {
            get {
                return ResourceManager.GetString("HtmlHeadingMigrationMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents.
        /// </summary>
        internal static string HtmlHeadingTableOfContents {
            get {
                return ResourceManager.GetString("HtmlHeadingTableOfContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generations over time.
        /// </summary>
        internal static string HtmlHeadingTimeline {
            get {
                return ResourceManager.GetString("HtmlHeadingTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        internal static string HtmlLangCode {
            get {
                return ResourceManager.GetString("HtmlLangCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string HtmlPopupDetails {
            get {
                return ResourceManager.GetString("HtmlPopupDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events: {0}.
        /// </summary>
        internal static string HtmlPopupEvents {
            get {
                return ResourceManager.GetString("HtmlPopupEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period: {0} - {1}.
        /// </summary>
        internal static string HtmlPopupPeriod {
            get {
                return ResourceManager.GetString("HtmlPopupPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average:.
        /// </summary>
        internal static string HtmlStatsAverage {
            get {
                return ResourceManager.GetString("HtmlStatsAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Births:.
        /// </summary>
        internal static string HtmlStatsBirths {
            get {
                return ResourceManager.GetString("HtmlStatsBirths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaths:.
        /// </summary>
        internal static string HtmlStatsDeaths {
            get {
                return ResourceManager.GetString("HtmlStatsDeaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Median:.
        /// </summary>
        internal static string HtmlStatsMedian {
            get {
                return ResourceManager.GetString("HtmlStatsMedian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} missing).
        /// </summary>
        internal static string HtmlStatsMissing {
            get {
                return ResourceManager.GetString("HtmlStatsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People:.
        /// </summary>
        internal static string HtmlStatsPeople {
            get {
                return ResourceManager.GetString("HtmlStatsPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Median lifespan.
        /// </summary>
        internal static string HtmlTimelineMedianLifespan {
            get {
                return ResourceManager.GetString("HtmlTimelineMedianLifespan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period: {0}-{1}.
        /// </summary>
        internal static string HtmlTimelinePeriod {
            get {
                return ResourceManager.GetString("HtmlTimelinePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kekule list.
        /// </summary>
        internal static string HtmlTitle {
            get {
                return ResourceManager.GetString("HtmlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (unknown).
        /// </summary>
        internal static string NameUnknown {
            get {
                return ResourceManager.GetString("NameUnknown", resourceCulture);
            }
        }
    }
}
